### ISSUE TITLE
Issue: CUDA driver version is insufficient for CUDA runtime version 

### ISSUE THREAD

**Issue by lc8631058** [facebookresearch/deepmask#102]
does anyone know that?
`th computeProposals.lua $DEEPMASK/pretrained/deepmask 
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-8932/cutorch/lib/THC/THCGeneral.c line=66 error=35 : CUDA driver version is insufficient for CUDA runtime version
/Users/congcong/torch/install/bin/luajit: /Users/congcong/torch/install/share/lua/5.1/trepl/init.lua:389: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /tmp/luarocks_cutorch-scm-1-8932/cutorch/lib/THC/THCGeneral.c:66
stack traceback:
	[C]: in function 'error'
	/Users/congcong/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	computeProposals.lua:11: in main chunk
	[C]: in function 'dofile'
	...cong/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x01006b3350`

**Comment by ziyan-wyq** [comment]
I'v met the problem. the solution is change the cuda version from 8 to 7.5.
sudo ln -s /usr/local/cuda  /usr/local/cuda-7.5

**Comment by lc8631058** [comment]
@ziyan-wyq thanks a lot
