### ISSUE TITLE
Coco module not found

### ISSUE THREAD

**Issue by saivineethkumar** [facebookresearch/deepmask#125]
Hi!
When I run the command: 
_th computeProposals.lua $DEEPMASK/pretrained/deepmask_

I am getting the following error:

_/home/sai/torch/install/bin/lua: /home/sai/torch/install/share/lua/5.2/trepl/init.lua:389: module 'coco' not found:No LuaRocks module found for coco
        no field package.preload['coco']
        no file '/home/sai/.luarocks/share/lua/5.2/coco.lua'
        no file '/home/sai/.luarocks/share/lua/5.2/coco/init.lua'
        no file '/home/sai/torch/install/share/lua/5.2/coco.lua'
        no file '/home/sai/torch/install/share/lua/5.2/coco/init.lua'
        no file '/home/sai/torch/install/lib/lua/5.2/coco.lua'
        no file '/home/sai/torch/install/lib/lua/5.2/coco/init.lua'
        no file './coco.lua'
        no file '/home/sai/.luarocks/lib/lua/5.2/coco.so'
        no file '/home/sai/torch/install/lib/lua/5.2/coco.so'
        no file '/home/sai/torch/install/lib/coco.so'
        no file '/home/sai/torch/install/lib/lua/5.2/loadall.so'
        no file './coco.so'
stack traceback:
        [C]: in function 'error'
        /home/sai/torch/install/share/lua/5.2/trepl/init.lua:389: in function 'require'
        computeProposals.lua:37: in main chunk
        [C]: in function 'dofile'
        .../sai/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: in ?_

I followed the instruction for installing all the packages including cocoapi from https://github.com/cocodataset/cocoapi , still I am getting the error.

can any one help me with this. I am new to this and could not figure out the issue
thanks!

**Comment by yzy1996** [comment]
same problem

**Comment by yzy1996** [comment]
I meet the same problem. How do you solve it?
