### ISSUE TITLE
Permissions denial for pre-trained models

### ISSUE THREAD

**Issue by SinghGaganpreet** [facebookresearch/deepmask#17]
Unable to download pre-trained files:
 1. wget https://s3.amazonaws.com/deepmask/models/deepmask/model.t7
 2. wget https://s3.amazonaws.com/deepmask/models/sharpmask/model.t7

**Comment by poliveirap** [comment]
This is weird, it is working here on my side.
Can you try to download in a different computer to see if the problem is in yours?

**Comment by SinghGaganpreet** [comment]
oh great it's working now, don't know why it was giving this error lately:
-------------------------
--2016-09-02 13:24:42--  https://s3.amazonaws.com/deepmask/models/sharpmask/model.t7
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.114.52
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.114.52|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 212312482 (202M) [application/octet-stream]
model.t7: Permission denied
----------------------

Thanks anyway.

**Comment by khanshab003** [comment]
@SinghGaganpreet You should try <b>'sudo'</b> before your command.
