### ISSUE TITLE
Out of memory on Titan X while running computeProposals.lua

### ISSUE THREAD

**Issue by navneet1083** [facebookresearch/deepmask#2]
Getting out of memory on Titan X while running computeProposals.lua with images. Default image works fine (i.e testImage.jpg) but it runs out of memory when i feed my testing images of dim : (3264x2448). Is there a restriction in image dimensions?

**Comment by soumith** [comment]
yes. the image dimensions need to be much smaller than that. try something in the order of 640 x 480

**Comment by navneet1083** [comment]
yup, it did work !!

**Comment by navneet1083** [comment]
It didn't work with mentioned one but much smaller than that (300-500).
