### ISSUE TITLE
Problem loading model

### ISSUE THREAD

**Issue by pannous** [facebookresearch/deepmask#20]
```
./computeProposals.lua $DEEPMASK/pretrained/deepmask 

| loading model file... /home/ex/torches/deepmask/pretrained/deepmask	
/opt/torch/install/bin/luajit: /home/ex/torches/deepmask/modelUtils.lua:41: attempt to call method 'replace' (a nil value)
stack traceback:
	/home/ex/torches/deepmask/modelUtils.lua:41: in function 'linear2convTrunk'
	/home/ex/torches/deepmask/DeepMask.lua:156: in function 'inference'
	./computeProposals.lua:51: in main chunk
	[C]: in function 'dofile'
	/opt/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d70


ls $DEEPMASK/pretrained/deepmask/
total 186004
drwxrwxr-x 2 ex      4096 Aug 26 21:02 .
drwxrwxr-x 4 ex      4096 Aug 26 21:02 ..
-rw-rw-r-- 1 ex 190265914 Aug 16 05:58 model.t7
```

**Comment by pannous** [comment]
similar:

`th evalPerPatch.lua $DEEPMASK/pretrained/sharpmask
| loading model file.../home/ex/torches/deepmask/pretrained/sharpmask	
/opt/torch/install/bin/luajit: /opt/torch/install/share/lua/5.1/threads/threads.lua:264: 
[thread 2 callback] /opt/torch/install/share/lua/5.1/coco/CocoApi.lua:126: assertion failed!
stack traceback:
	[C]: in function 'assert'
	/opt/torch/install/share/lua/5.1/coco/CocoApi.lua:126: in function '__init'
	/opt/torch/install/share/lua/5.1/torch/init.lua:91: in function </opt/torch/install/share/lua/5.1/torch/init.lua:87>
	[C]: in function 'CocoApi'
	/home/ex/torches/deepmask/DataSampler.lua:26: in function '__init'
	/opt/torch/install/share/lua/5.1/torch/init.lua:91: in function </opt/torch/install/share/lua/5.1/torch/init.lua:87>
	[C]: in function 'DataSampler'
	/home/ex/torches/deepmask/DataLoader.lua:37: in function </home/ex/torches/deepmask/DataLoader.lua:31>
	[C]: in function 'xpcall'
	/opt/torch/install/share/lua/5.1/threads/threads.lua:231: in function 'callback'
	/opt/torch/install/share/lua/5.1/threads/queue.lua:65: in function </opt/torch/install/share/lua/5.1/threads/queue.lua:41>
	[C]: in function 'pcall'
	/opt/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
	[string "  local Queue = require 'threads.queue'..."]:13: in main chunk
[thread 1 callback] /opt/torch/install/share/lua/5.1/coco/CocoApi.lua:126: assertion failed!
stack traceback:
	[C]: in function 'assert'
	/opt/torch/install/share/lua/5.1/coco/CocoApi.lua:126: in function '__init'
	/opt/torch/install/share/lua/5.1/torch/init.lua:91: in function </opt/torch/install/share/lua/5.1/torch/init.lua:87>
	[C]: in function 'CocoApi'
	/home/ex/torches/deepmask/DataSampler.lua:26: in function '__init'
	/opt/torch/install/share/lua/5.1/torch/init.lua:91: in function </opt/torch/install/share/lua/5.1/torch/init.lua:87>
	[C]: in function 'DataSampler'
	/home/ex/torches/deepmask/DataLoader.lua:37: in function </home/ex/torches/deepmask/DataLoader.lua:31>
	[C]: in function 'xpcall'
	/opt/torch/install/share/lua/5.1/threads/threads.lua:231: in function 'callback'
	/opt/torch/install/share/lua/5.1/threads/queue.lua:65: in function </opt/torch/install/share/lua/5.1/threads/queue.lua:41>
	[C]: in function 'pcall'
	/opt/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
	[string "  local Queue = require 'threads.queue'..."]:13: in main chunk
stack traceback:
	[C]: in function 'error'
	/opt/torch/install/share/lua/5.1/threads/threads.lua:264: in function 'synchronize'
	/opt/torch/install/share/lua/5.1/threads/threads.lua:142: in function 'specific'
	/opt/torch/install/share/lua/5.1/threads/threads.lua:125: in function 'Threads'
	/home/ex/torches/deepmask/DataLoader.lua:41: in function '__init'
	/opt/torch/install/share/lua/5.1/torch/init.lua:91: in function </opt/torch/install/share/lua/5.1/torch/init.lua:87>
	[C]: in function 'DataLoader'
	/home/ex/torches/deepmask/DataLoader.lua:22: in function 'create'
	evalPerPatch.lua:75: in main chunk
	[C]: in function 'dofile'
	/opt/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d70
`

**Comment by szagoruyko** [comment]
@pannous ```luarocks install nn; luarocks install inn```
probably you will need to update cutorch and cunn as well

**Comment by poliveirap** [comment]
Sergey suggestion should have worked. 
I'll close this issue, if you still have trouble, just re-open it.

**Comment by gkv91** [comment]
Hi, when i am trying to do th tarantula i am getting the following error. Can anyone please help me to resolve the error?
deepmask-master/modelUtils.lua:73: attempt to call local 'nn_padding' (a nil value)
