### ISSUE TITLE
error loading model

### ISSUE THREAD

**Issue by yanyuxiaoxiao** [facebookresearch/deepmask#21]
When I load deepmask model and sharpmask model in computeProposals.lua. Some error seem strange.
![image](https://cloud.githubusercontent.com/assets/12267543/18264613/e16fd5b6-7443-11e6-81c7-a4c77c4b0df2.png)
![image](https://cloud.githubusercontent.com/assets/12267543/18264616/ea402db2-7443-11e6-94fc-8cacff4b13b3.png)
This is the two models md5sum result:
b4db9112a422acf74c75c9c15bbc3987  deepmask/model.t7
1767d49a3150617b9abfcd054c135afb  sharpmask/model.t7

How to handle the error. Is the model.t7 problem or anything else?

**Comment by poliveirap** [comment]
The models seem to be correct.
Are you using torch with lua or luajit? Maybe try with luajit to see if it works.

**Comment by yanyuxiaoxiao** [comment]
@poliveirap Thank you! It works when swith to luajit. But! What's the different between  lua and luajit using torch?

**Comment by poliveirap** [comment]
Cool.
luajit is a (faster, but with an annoying memory limitation) variation of lua and torch can be built upon both of them.
