### ISSUE TITLE
wrong number of arguments for function call

### ISSUE THREAD

**Issue by etali** [facebookresearch/deepmask#22]
When I ran "th computeProposals.lua $DEEPMASK/pretrained/deepmask", I got the following error information. Do you have any idea about this problem?

/data00/liyitan/torch/install/share/lua/5.1/nn/THNN.lua:109: wrong number of arguments for function call
stack traceback:
        [C]: in function 'v'
        /data00/liyitan/torch/install/share/lua/5.1/nn/THNN.lua:109: in function 'SpatialMaxPooling_updateOutput'
        ...tan/torch/install/share/lua/5.1/nn/SpatialMaxPooling.lua:42: in function <...tan/torch/install/share/lua/5.1/nn/SpatialMaxPooling.lua:31>
        [C]: in function 'xpcall'
        ...a00/liyitan/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        ...00/liyitan/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        /data00/liyitan/repos/deepmask/InferDeepMask.lua:100: in function 'forward'
        computeProposals.lua:81: in main chunk
        [C]: in function 'dofile'
        ...itan/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00405d70

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
        [C]: in function 'error'
        ...a00/liyitan/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
        ...00/liyitan/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        /data00/liyitan/repos/deepmask/InferDeepMask.lua:100: in function 'forward'
        computeProposals.lua:81: in main chunk
        [C]: in function 'dofile'
        ...itan/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00405d70

**Comment by soumith** [comment]
@etali your nn and cunn packages seem to be out of sync maybe.

Run:
luarocks install nn
luarocks install cunn

**Comment by etali** [comment]
Thank you so much.
I run "luarocks install nn" and "luarocks install cunn" , then it works.
