### ISSUE TITLE
Permission denied (publickey). fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by mrtortong** [facebookresearch/deepmask#23]
Hi.

root@tong:/# git clone git@github.com:facebookresearch/deepmask.git $DEEPMASK
Cloning into '/desired/absolute/path/to/deepmask'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Please recommend.
mrtortong.

**Comment by tylin** [comment]
It seems the problem might be using git under root:
http://stackoverflow.com/questions/15696190/permission-denied-when-cloning-git-repository
https://help.github.com/articles/error-permission-denied-publickey/

**Comment by mr1528** [comment]
to mrtortong  :
use this 
https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

then get your generated key ( start with ssh-rsa or other type )
go to your git user panel -> SSH & GPG Keys  --> New SSH key -> paste your key ( fill title with any ) then press Add SSH key 

Will Fix.

good luck.

**Comment by Gwennyphar** [comment]
my solution was
Generate SSH key using ssh-keygen -t rsa -b 4096 -C "your_email@example.com".
Copy the output of cat id_rsa.pub
Paste the above copied outpur into your Github profile -> Settings ->
SSH and GPG Keys -> Add new SSH key

**Comment by zazapeta** [comment]
I did what @Gwennyphar said +

 ```ssh-add -K ~/.ssh/<YOUR_GENERATED_RSA_FILE>```

I found this article : https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#adding-your-ssh-key-to-the-ssh-agent

Cheers 🍺

**Comment by ChristophKnopf** [comment]
When you're facing this little fellow `Could not open a connection to your authentication agent.`
Go here [Start Agent for the bash (Stackoverflow)](https://stackoverflow.com/questions/17846529/could-not-open-a-connection-to-your-authentication-agent)
I had to do as the ssh agent was not found but running!
