### ISSUE TITLE
Error when luarocks install

### ISSUE THREAD

**Issue by mrtortong** [facebookresearch/deepmask#24]
Hi

When i run "luarocks install cunn"
and image, tds, cjson, nnx, optim, inn, cutorch, cunn, cudnn 

-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_cutorch-scm-1-5467/cutorch/build/CMakeFiles/CMakeOutput.log".

Error: Failed installing dependency: https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec - Build error: Failed building.

Please recommend
mrtortong

**Comment by SJTUsuperxu** [comment]
It might be the problem of your network(I mean Internet). I also spent plenty of time to try it. Just never stop luarocks install ..
