### ISSUE TITLE
no field package.preload['cutorch']

### ISSUE THREAD

**Issue by mrtortong** [facebookresearch/deepmask#25]
Hi

	no field package.preload['cutorch']
	no file '/root/.luarocks/share/lua/5.1/cutorch.lua'
	no file '/root/.luarocks/share/lua/5.1/cutorch/init.lua'
	no file '/root/torch/install/share/lua/5.1/cutorch.lua'
	no file '/root/torch/install/share/lua/5.1/cutorch/init.lua'
	no file './cutorch.lua'
	no file '/root/torch/install/share/luajit-2.1.0-beta1/cutorch.lua'
	no file '/usr/local/share/lua/5.1/cutorch.lua'
	no file '/usr/local/share/lua/5.1/cutorch/init.lua'
	no file '/root/.luarocks/lib/lua/5.1/cutorch.so'
	no file '/root/torch/install/lib/lua/5.1/cutorch.so'
	no file '/root/torch/install/lib/cutorch.so'
	no file './cutorch.so'
	no file '/usr/local/lib/lua/5.1/cutorch.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/root/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	computeProposals.lua:11: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d50

Please recommend.
mrtortong.

**Comment by Alek-dr** [comment]
Seems like you should install cutorch.
try do this:
luarocks install cutorch
