### ISSUE TITLE
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-4143/cutorch/lib/THC/THCGeneral.c line=20 error=38 : no CUDA-capable device is detected

### ISSUE THREAD

**Issue by mrtortong** [facebookresearch/deepmask#28]
Hi,

Please help me.

Please make sure you have the correct access rights
and the repository exists.
root@tong:/# git clone https://github.com/facebookresearch/deepmask.git $DEEPMASK
Cloning into '/desired/absolute/path/to/deepmask'...
remote: Counting objects: 58, done.
remote: Total 58 (delta 0), reused 0 (delta 0), pack-reused 58
Unpacking objects: 100% (58/58), done.
Checking connectivity... done.
root@tong:/# mkdir -p $DEEPMASK/pretrained/deepmask; cd $DEEPMASK/pretrained/deepmask
root@tong:/desired/absolute/path/to/deepmask/pretrained/deepmask# wget https://s3.amazonaws.com/deepmask/models/deepmask/model.t7
--2016-09-11 16:13:59--  https://s3.amazonaws.com/deepmask/models/deepmask/model.t7
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.115.42
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.115.42|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 190265914 (181M) [application/octet-stream]
Saving to: ‘model.t7’

100%[====================================================================>] 190,265,914 2.49MB/s   in 2m 9s  

2016-09-11 16:16:09 (1.41 MB/s) - ‘model.t7’ saved [190265914/190265914]

root@tong:/desired/absolute/path/to/deepmask/pretrained/deepmask# cd /
root@tong:/# mkdir -p $DEEPMASK/pretrained/sharpmask; cd $DEEPMASK/pretrained/sharpmask
root@tong:/desired/absolute/path/to/deepmask/pretrained/sharpmask# wget https://s3.amazonaws.com/deepmask/models/sharpmask/model.t7
--2016-09-11 16:16:52--  https://s3.amazonaws.com/deepmask/models/sharpmask/model.t7
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.17.96
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.17.96|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 212312482 (202M) [application/octet-stream]
Saving to: ‘model.t7’

40% [==============================>                                              ] 85,677,701   106KB/s  eta 12m 3100%[====================================================================>] 212,312,482  114KB/s   in 26m 33s

2016-09-11 16:43:27 (130 KB/s) - ‘model.t7’ saved [212312482/212312482]

root@tong:/desired/absolute/path/to/deepmask/pretrained/sharpmask# cd $DEEPMASK
root@tong:/desired/absolute/path/to/deepmask# th computeProposals.lua $DEEPMASK/pretrained/deepmask
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-4143/cutorch/lib/THC/THCGeneral.c line=20 error=38 : no CUDA-capable device is detected
/root/torch/install/bin/lua: /root/torch/install/share/lua/5.2/trepl/init.lua:384: cuda runtime error (38) : no CUDA-capable device is detected at /tmp/luarocks_cutorch-scm-1-4143/cutorch/lib/THC/THCGeneral.c:20
stack traceback:
	[C]: in function 'error'
	/root/torch/install/share/lua/5.2/trepl/init.lua:384: in function 'require'
	computeProposals.lua:11: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: in ?
root@tong:/desired/absolute/path/to/deepmask# th computeProposals.lua $DEEPMASK/pretrained/sharpmask
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-4143/cutorch/lib/THC/THCGeneral.c line=20 error=38 : no CUDA-capable device is detected
/root/torch/install/bin/lua: /root/torch/install/share/lua/5.2/trepl/init.lua:384: cuda runtime error (38) : no CUDA-capable device is detected at /tmp/luarocks_cutorch-scm-1-4143/cutorch/lib/THC/THCGeneral.c:20
stack traceback:
	[C]: in function 'error'
	/root/torch/install/share/lua/5.2/trepl/init.lua:384: in function 'require'
	computeProposals.lua:11: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: in ?

Thank you in advance.
mrtortong

**Comment by rnicholus** [comment]
Looks like you don't have an nVidia CUDA GPU on your machine. You can grab an EC2 instance for this purpose. I used this one https://aws.amazon.com/marketplace/pp/B00FYCDDTE?qid=1474037260500&sr=0-1&ref_=srh_res_product_title.
