### ISSUE TITLE
Problem in hardware.Right? (CUDA-capable GPU)

### ISSUE THREAD

**Issue by mrtortong** [facebookresearch/deepmask#29]
Hi.
Please recommend.
my notebook is http://specsnotebook.blogspot.com/2011/03/laptop-asus-a42j.html
Video Type
ATI Mobility Radeon HD 5470 1GB

it can use

CUDA-capable GPU
A supported version of Linux with a gcc compiler and toolchain
NVIDIA CUDA Toolkit (available at http://developer.nvidia.com/cuda-downloads) 

Or not.

Thank you.
mrtortong

**Comment by soumith** [comment]
closed via https://github.com/facebookresearch/deepmask/issues/29
