### ISSUE TITLE
No rights to access deepmask git repo  

### ISSUE THREAD

**Issue by albertyou2** [facebookresearch/deepmask#33]
Hi  Deep guys:

I 'am  cloning  deepmask git repo by using  this command: 

git clone git@github.com:facebookresearch/deepmask.gi

But I met access right problem when it started as beblow:

warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Does any one know how to  handle this?
Thank you !

**Comment by tylin** [comment]
You might have same issue like https://github.com/facebookresearch/deepmask/issues/23

**Comment by albertyou2** [comment]
Yes I think they are the same.
Thank you

**Comment by venkateshakkisetty** [comment]
same issue 
Warning: Permanently added the RSA host key for IP address '192.30.255.113' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
