### ISSUE TITLE
Can't to install COCO API, cjson

### ISSUE THREAD

**Issue by JingjingZhangAndPan** [facebookresearch/deepmask#40]
Dear, Developer,
when I try to install deepmask and sharpmask tool,
I can't install COCO API, and cjson which need by tools,

linux@linux:~/work$ luarocks install COCO API
Error: No results matching query were found.

could you guide me how to install torch package of COCO API and cjson?

Thanks.

**Comment by mbuckler** [comment]
Hi there, you can find the COCO API as well as its installation instructions here: https://github.com/pdollar/coco
