### ISSUE TITLE
loop or previous error loading module 'tds'

### ISSUE THREAD

**Issue by geekvc** [facebookresearch/deepmask#41]
when I ran th train.lua , 
I got the error :

``` sh
FATAL THREAD PANIC: (pcall) not enough memory , 
```

so I reinstalled the lua 5.1 ,which doesn't have the same memory limitation (I saw in the issue [#80](https://github.com/karpathy/char-rnn/issues/80)) , the problem solved.
and I got another error:

``` sh
convert: data//annotations/instances_train2014.json --> .t7 [please be patient]
convert: data//annotations/instances_train2014.json --> .t7 [please be patient]
converting: categories
converting: categories
converting: annotations
converting: annotations
converting: images
converting: images
convert: building indices
convert: building indices
convert: complete [46.12 s]convert: complete [46.17 s]
DataSampler.lua:12: loop or previous error loading module 'tds'
```

I do not know where has already required the package 'tds'.
I removed the DataSampler.lua:12    local tds = require 'tds'
another occured:

``` sh
DataSampler.lua:67: attempt to index global 'tds' (a nil value)
```

Can you help me ?
thank you!

**Comment by ytian90** [comment]
Hi, I have some kind of same problem before, the reason is because you are missing the module of 'tds', follow the [link](https://github.com/torch/tds) for more information about 'tds' and [this](https://github.com/facebook/luaffifb) for installation. Hope it helps!

**Comment by geekvc** [comment]
The bug was fixed , 
Thank you very much! @ytian90
