### ISSUE TITLE
How to train sharpmask on my own dataset?

### ISSUE THREAD

**Issue by brisker** [facebookresearch/deepmask#46]
How to train sharpmask on my own dataset?

**Comment by tongerpeng** [comment]
you have trained deepmask on your own images?

**Comment by brisker** [comment]
@tongerpeng     no..

**Comment by tongerpeng** [comment]
I want to train model with my own images, but it is so annoy to create the COCO annotation json file

**Comment by brisker** [comment]
@tongerpeng 
You labeled your own dataset? instance-level annotation?
dog 1  0-1 
dog 2  0-2
cat  1  1-1
cat  2   1-2
etc..
Like this?

**Comment by tongerpeng** [comment]
@brisker like this
 {
"info": info,
"images": [image],
"annotations": [annotation],
"licenses": [license],
}

see details: mscoco.org/dataset/#Download

**Comment by brisker** [comment]
@tongerpeng 
how to install the dependencies of torch?

**Comment by tongerpeng** [comment]
download coco api, there is a file, LuaAPI/rocks/ coco-scm-1.rockspec.  Then, run: luarocks install coco-scm-1.rockspec

**Comment by brisker** [comment]
@tongerpeng 
Why an image as simple as this ,the sharpmask still neglect two dogs in just five dogs, why the performance so low?
![image](https://cloud.githubusercontent.com/assets/13804492/19555062/d62e9440-96ed-11e6-816b-ce95f6ff821e.png)

**Comment by tongerpeng** [comment]
@brisker yes, the accuracy is not high. In addition, the default proposal is 5, you can set the option with -np in computeproposals.lua

**Comment by brisker** [comment]
@tongerpeng   
any idea?
I tried to train using another code, but this error: 
~/torch/install/bin/luajit: inconsistent tensor size at ~/torch/pkg/torch/lib/TH/generic/THTensorCopy.c:7
stack traceback:
[C]: at 0x7f7115a75580
[C]: in function 'reshape'
./plants_utils.lua:84: in function 'create_instance'
experiment.lua:243: in main chunk
[C]: in function 'dofile'
...code/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
[C]: at 0x00406670

any idea?

**Comment by tongerpeng** [comment]
@brisker no, I don't konw totoally  :(

**Comment by khanshab003** [comment]
@brisker Can you please share the steps on how to train model for deepmask and how to prepare data for training using COCO API? A concrete example of annotations file including the image will be highly appreciated.

**Comment by dexter1608** [comment]
@farooqkhan003  did you find any answer?

**Comment by farooqkhan003** [comment]
@dexter1608 no. :/
