### ISSUE TITLE
ERROR: could not insert 'nvidia_367_uvm': Required key not available.

### ISSUE THREAD

**Issue by JingjingZhangAndPan** [facebookresearch/deepmask#48]
Dear sir,
when I run computerProposals.lua with deepmask, "ERROR: could not insert 'nvidia_367_uvm': Required key not available." error will be happened, could you guide me how to fix this issue, thanks.

**Comment by poliveirap** [comment]
Hi, I havent seen this error before.
The problem is gpu-related and not really related to this project.
Could you maybe try to update cudnn, cunn, nn to see if it works?
