### ISSUE TITLE
SharpMask Without Normalization?

### ISSUE THREAD

**Issue by XiongweiWu** [facebookresearch/deepmask#51]
Hi, thx for your excellent work! When I run the sharpmask code I find you have not performed normalization before feature concatenation. I wonder whether it will perform better if adding normalization between different layers' features.

**Comment by poliveirap** [comment]
We did not try it. I'm not sure it would help, since it contains convolutions (both on horizontal and vertical paths) and they should learn how to merge the information from the low-level features and low-level enconding
