### ISSUE TITLE
Fine tuning

### ISSUE THREAD

**Issue by moh3th1** [facebookresearch/deepmask#52]
How to fine tune your model?
I don't have sufficient data to retrain your model from scratch.
I want to fine tune your model on my data which has only two classes ?

**Comment by poliveirap** [comment]
In this case you would have to change the DataSampler.lua file. The way it is, it will sample data from COCO. You have to modify it to use the data you want to.
It basically needs to have a DataSampler:get() function that outputs an input patch and its label.
