### ISSUE TITLE
How do you get the bounding box annotations coco json for an image

### ISSUE THREAD

**Issue by ranjit-** [facebookresearch/deepmask#55]

**Comment by poliveirap** [comment]
For that, check the official COCO API here:
http://mscoco.org/dataset/#download

**Comment by hazirbas** [comment]
@ranjit- you can refer to my implementation:

[coco-json-converter](https://github.com/hazirbas/coco-json-converter)

**Comment by gabriellap** [comment]
@hazirbas I keep getting the following error when I run your code on my dataset:
  File "generate_coco_json.py", line 155, in <module>
    Image.fromarray(c.annToMask(c.loadAnns([255])[0])*255).show()
  File "/usr/local/lib/python2.7/dist-packages/pycocotools/coco.py", line 207, in loadAnns
    return [self.anns[id] for id in ids]
KeyError: 255
Have you ever encountered this error?

**Comment by hazirbas** [comment]
255 is ignore label? Maybe swap labels 0 and 255 in your maps?

**Comment by gabriellap** [comment]
Thank you for your help and for providing the code to generate it. My dataset has multiple objects in the image such as car, cup, etc. and in the DAVIS dataset each image has only one label. Any ideas how I could tackle this problem?
