### ISSUE TITLE
Are the evalPerPatch.lua and  evalPerImage.lua files not support -save option?

### ISSUE THREAD

**Issue by dearhoper** [facebookresearch/deepmask#57]
Why do the following commands run failed when the -save option is specified? Is the -save option not implemented yet ?

`> th evalPerPatch.lua exps/deepmask/exp/ -save true`
or
`> th evalPerImage.lua exps/deepmask/exp/ -save true`

`invalid argument: true	`
`Usage: [options] <model>`

`per patch evaluation of DeepMask/SharpMask`

`  <model>      model to load`
`Options:`
`  -seed        Manually set RNG seed [1]`
`  -gpu         gpu device [1]`
`  -testmaxload max number of testing batches [200]`
`  -save        save output [false]`

**Comment by poliveirap** [comment]
Hi,
'save' argument is boolean, so the way to use it is:
th evalPerPatch.lua exps/deepmask/exp/ -save
(ie, no need to add 'true' after it)

**Comment by dearhoper** [comment]
Thanks! :+1:
