### ISSUE TITLE
How do I train my own dataset?

### ISSUE THREAD

**Issue by Aggr0vatE** [facebookresearch/deepmask#59]
Hi everybody,

I was wondering how I train my own dataset. I searched everywhere online and couldn't find an answer/tutorial so I decided to ask this question.

I am sure there are people who have already done this, so I was wondering if you could help me and give me tips.

Thanks!

Stephen

**Comment by poliveirap** [comment]
Hi,
In this case you need to modify DataSampler.lua file.
The function get() there returns a RGB input patch and a label (which is either the ground truth mask or a +1/-1 score, depending on which head the batch is training).
Assuming your modify this function, the rest should work.

**Comment by Aggr0vatE** [comment]
Thank you for the response. I have another question however, as I am new to this and lua/torch programming. I am looking through the DataSampler.lua file right now and I was wondering what line this function you mention is located. Thank you for the response!
