### ISSUE TITLE
How can I resolve the following THNN errors?

### ISSUE THREAD

**Issue by yxchng** [facebookresearch/deepmask#60]
not found: THNN_CudaHalfELU_updateOutput/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfELU_updateGradInput/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfHardTanh_updateOutput/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfHardTanh_updateGradInput/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfLeakyReLU_updateOutput/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfLeakyReLU_updateGradInput/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfLookupTable_accGradParameters/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type
not found: THNN_CudaHalfLookupTable_renorm/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfMarginCriterion_updateOutput/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type
not found: THNN_CudaHalfMarginCriterion_updateGradInput/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfMultiMarginCriterion_updateOutput/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfMultiMarginCriterion_updateGradInput/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfPReLU_accGradParameters/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfSpatialConvolutionLocal_accGradParameters/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfSpatialConvolutionMM_accGradParameters/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfSpatialCrossMapLRN_updateOutput/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfSpatialCrossMapLRN_updateGradInput/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfSpatialDilatedConvolution_accGradParameters/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfSpatialFullConvolution_accGradParameters/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfSoftPlus_updateOutput/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfSoftPlus_updateGradInput/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfSoftShrink_updateOutput/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfSoftShrink_updateGradInput/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfSqrt_updateOutput/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfTemporalConvolution_accGradParameters/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfThreshold_updateOutput/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfThreshold_updateGradInput/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfVolumetricConvolution_accGradParameters/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfVolumetricDilatedConvolution_accGradParameters/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
not found: THNN_CudaHalfVolumetricFullConvolution_accGradParameters/home/yxchng/torch/install/share/lua/5.2/nn/THNN.lua:108: NYI: call arg type	
-- ignore option datadir	
-- ignore option dm	
-- ignore option rundir	
-- ignore option gpu	
-- ignore option reload	
| running in directory /home/yxchng/segment/deepmask/exps/deepmask/exp	
| number of paramaters trunk: 15198016	
| number of paramaters mask branch: 1608768	
| number of paramaters score branch: 526337	
| number of paramaters total: 17333121

**Comment by poliveirap** [comment]
Hi,
I havent seen this error before, but i dont think the error is related to this project.
I think that assuming your GPU has enough memory and the package dependencies (cudnn, cunn, nn) are up-to-date, this should not show up.

**Comment by chenyanlu** [comment]
Hi, @yxchng 
I get the same error,how do you solve it? Thank you so much.

**Comment by yxchng** [comment]
I used luajit instead of 5.2
