### ISSUE TITLE
How to interpret the result of evalPerImage.lua?

### ISSUE THREAD

**Issue by yxchng** [facebookresearch/deepmask#62]
{
        "category_id": 1, 
        "image_id": 1089, 
        "score": 0.048549108207226, 
        "segmentation": {
            "counts": "]lW35ca0?D7J4L4K5L3M4L3N3L4L:F2N2N2O0O1O1O2M2O2N1N200O2N1O1O001M3O1O2N0O2N101O00000000KZASMg>m24OO3M2O01001O0001O1O1N1O101M3N2M3M3M3M3O1N2O1M4N2M1O2N2O2N1\\NP@Y1S`0fNo_OW1R`0hNP@V1S`0hNn_OV1T`0hNm_OW1^`0N2N2NNPOY_On0i`0_OY_O0i`00Y_OBO2o`0:=1OO1N1011N2O10O1M2N3O2N1NPbX6", 
            "size": [
                573, 
                640
            ]
        }
    }, 

Can I know what is "counts"? How to I get the real "counts"?. Thanks.

**Comment by poliveirap** [comment]
counts is the the segmentation mask encoded using RLE. This is the COCO official way to store segmentation masks (it saves a good amount of space if compared to storing the whole binary mask for each proposal).
To decode it into binary tensor, you need to use to official COCO API (https://github.com/pdollar/coco)
