### ISSUE TITLE
Where in the code is the application of inference with 16 pixel stride done? (mentioned in the paper)

### ISSUE THREAD

**Issue by yxchng** [facebookresearch/deepmask#69]
According to the Deepmask paper, it says "... During full image inference we apply the model densely at multiple locations (with a stride of 16 pixels)...". However, I can't seem to find in the code where this application of inference with 16 pixel stride is done. Can you kindly point me to the relevant part in the code? Thanks.

**Comment by poliveirap** [comment]
the stride of 16 comes automatically form the pooling layers (4 2x2 max pooling layers on the whole network). If you input an image of size HxW, the output will be H/16xW/16 for both outputs.
