### ISSUE TITLE
How to Compute proposals with batch

### ISSUE THREAD

**Issue by abrahamyan-lusine** [facebookresearch/deepmask#70]
How to get proposals for batch(several images on GPU) instead of evaluation one by one, with computeProposals.lua?

**Comment by poliveirap** [comment]
Hi, since test images does not have the same dimensions, we chose not to process them in batch mode, so we do one-by-one. 
To make it work, some small modifications need to be made on InferDeepMask.lua/InferSharpMask.lua files.

**Comment by abrahamyan-lusine** [comment]
Can you please provide some more information on how to modify InferDeepMask?
