### ISSUE TITLE
Error running the quick start

### ISSUE THREAD

**Issue by suhalim9** [facebookresearch/deepmask#8]
Hi,

I am trying to run the quick start, and I get this error. Could you please advise?

/home/ai2-c3p0/torch/install/bin/luajit: cannot open </home/ai2-c3p0/Documents/code/k_working_directory/deepmask/sharpmask/model.t
7> in mode r  at /home/ai2-c3p0/torch/pkg/torch/lib/TH/THDiskFile.c:649                                                             
stack traceback:                                                                                                                    
        [C]: at 0x7f8cf053d7b0                                                                                                      
        [C]: in function 'DiskFile'                                                                                                 
        /home/ai2-c3p0/torch/install/share/lua/5.1/torch/File.lua:405: in function 'load'                                           
        computeProposals.lua:48: in main chunk                                                                                      
        [C]: in function 'dofile'                                                                                                   
        ...c3p0/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk                                              
        [C]: at 0x00406670     

Thanks,

**Comment by poliveirap** [comment]
The problem seems to be when loading the pretrained model.
Are you sure you have them on the right place (or point to the place where the pretrained models are placed)?
eg: th computeProposals.lua $DEEPMASK/pretrained/sharpmask (note that you dont need to include the '/model.t7' on this path)

**Comment by suhalim9** [comment]
@poliveirap,

th computeProposals.lua $DEEPMASK/pretrained/deepmask # run DeepMask
th computeProposals.lua $DEEPMASK/pretrained/sharpmask # run SharpMask
th computeProposals.lua $DEEPMASK/sharpmask -img /path/to/image.jpg

Here, The first two commands run fine and complete without any error. The third line is where I get stuck. I am wondering if I am supposed to see a folder/file named sharpmask..? Because there is nothing named sharpmask in the github

**Comment by poliveirap** [comment]
Ah, indeed thrdis line is wrong. It should be the same as the others. Third line should be:
th computeProposals.lua $DEEPMASK/pretrained/sharpmask -img /path/to/img

**Comment by suhalim9** [comment]
That's what I thought.. It runs just fine now! One more thing since I have you haha. What's expected output? Should I expect an image file in some other folder?

Thank you so much for your kind response

**Comment by poliveirap** [comment]
cool :)
The output should be an image, $DEEPMASK/pretrained/sharpmask/res.jpg , which is RGB image you give on input with the proposed masks. (if you want something else, for example the proposals, you need to modify the code (line 84 get the proposals on 'mask' variable)

**Comment by poliveirap** [comment]
Can I close this now?

**Comment by suhalim9** [comment]
I found the res.jpg in $DEEPMASK folder. Thank you so much for your help.

**Comment by Alek-dr** [comment]
Hi, somebody known what's the problem? Help please

alexander@alexander-X550MJ:~/DeepMask$ th computeProposals.lua $DEEPMASK/pretrained/deepmask
Found Environment variable CUDNN_PATH = /home/alexander/cuda_nn/lib64	
/home/alexander/torch/install/bin/luajit: /home/alexander/torch/install/share/lua/5.1/trepl/init.lua:384: /home/alexander/torch/install/share/lua/5.1/trepl/init.lua:384: /home/alexander/torch/install/share/lua/5.1/cudnn/ffi.lua:1592: /home/alexander/cuda_nn/lib64: cannot read file data: Is a directory
stack traceback:
	[C]: in function 'error'
	/home/alexander/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	/home/alexander/DeepMask/DeepMask.lua:18: in main chunk
	[C]: in function 'dofile'
	computeProposals.lua:44: in main chunk
	[C]: in function 'dofile'
	...nder/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d50

**Comment by soumith** [comment]
yes. you have the environment variable CUDNN_PATH set. It should actually be set to the full library path, i.e.
CUDNN_PATH="/home/alexander/cuda_nn/lib64/libcudnn.so"

**Comment by Alek-dr** [comment]
@soumith 
Thank you very much. I think this problem is solved. But I faced another problem:

/home/alexander/torch/install/bin/lua: ...alexander/torch/install/share/lua/5.1/trepl/init.lua:384: module 'inn' not found:No LuaRocks module found for inn
	no field package.preload['inn']
.......
......

If I try install inn:

[ 33%] Building NVCC (Device) object CMakeFiles/inn.dir/inn_generated_SpatialStochasticPooling.cu.o
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
CMake Error at inn_generated_SpatialStochasticPooling.cu.o.cmake:267 (message):
  Error generating file
  /tmp/luarocks_inn-1.0-0-5705/imagine-nn/build/CMakeFiles/inn.dir//./inn_generated_SpatialStochasticPooling.cu.o


CMakeFiles/inn.dir/build.make:70: ошибка выполнения рецепта для цели «CMakeFiles/inn.dir/inn_generated_SpatialStochasticPooling.cu.o»
make[2]: *** [CMakeFiles/inn.dir/inn_generated_SpatialStochasticPooling.cu.o] Ошибка 1
CMakeFiles/Makefile2:67: ошибка выполнения рецепта для цели «CMakeFiles/inn.dir/all»
make[1]: *** [CMakeFiles/inn.dir/all] Ошибка 2
Makefile:127: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2

Error: Build error: Failed building.

**Comment by mrtortong** [comment]
Hi soumith or somebody 

[C]: in function 'error'
	/usr/local/share/lua/5.1/trepl/init.lua:384: in function 'require'
	/desired/absolute/path/to/deepmask/DeepMask.lua:18: in main chunk
	[C]: in function 'dofile'
	computeProposals.lua:44: in main chunk
	[C]: in function 'dofile'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406260
 
export CUDNN_PATH=/usr/local/cuda-8.0/lib64
 cuda-8.0 only has libcuda.so 

Please recommend.

**Comment by idonknow** [comment]
i have a same error as you ,but it occurs when i run the sharpmask ;
th computeProposals.lua $DEEPMASK/pretrained/sharpmask # run SharpMask
how could i deal with it
@suhalim9 @poliveirap

**Comment by mrtortong** [comment]
/etc/profile.d 
create file cuda.sh
export PATH=/usr/local/cuda-8.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64\${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export CUDNN_PATH=/usr/local/cuda-8.0/lib64/libcudnn.so.5
 3 line in cuda.sh save and restart.

**Comment by liketheflower** [comment]
I got the same error and here is the error and solution:
error:  

/home/ec2-user/torch/install/bin/luajit: cannot open </pretrained/deepmask/model.t7> in mode r at /home/ec2-user/torch/pkg/torch/lib/TH/THDiskFile.c:670 stack traceback: [C]: at 0x7fd6ce4b32c0 [C]: in function 'DiskFile' /home/ec2-user/torch/install/share/lua/5.1/torch/File.lua:405: in function 'load' computeProposals.lua:49: in main chunk [C]: in function 'dofile' ...user/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:151: in main chunk [C]: at 0x004064c0

#  solution
luarocks install json  

json is not installed so I got the error.  
after the installation of json, problem solved.
