### ISSUE TITLE
How solve this problem ,when i run  [evalPerPatch.lua ]?

### ISSUE THREAD

**Issue by chenyanlu** [facebookresearch/deepmask#80]
{when i run this :}

th evalPerPatch.lua ./pretrained/sharpmask/

{then :}

| loading model file..../pretrained/sharpmask/	
/home/vr/torch/install/bin/luajit: /home/vr/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 1 callback] /home/vr/torch/install/share/lua/5.1/coco/CocoApi.lua:126: assertion failed!
stack traceback:
	[C]: in function 'assert'
	/home/vr/torch/install/share/lua/5.1/coco/CocoApi.lua:126: in function '__init'
	/home/vr/torch/install/share/lua/5.1/torch/init.lua:91: in function </home/vr/torch/install/share/lua/5.1/torch/init.lua:87>
	[C]: in function 'CocoApi'
	/home/vr/deepmask/DataSampler.lua:24: in function '__init'
	/home/vr/torch/install/share/lua/5.1/torch/init.lua:91: in function </home/vr/torch/install/share/lua/5.1/torch/init.lua:87>
	[C]: in function 'DataSampler'
	/home/vr/deepmask/DataLoader.lua:37: in function </home/vr/deepmask/DataLoader.lua:32>
	[C]: in function 'xpcall'
	/home/vr/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
	/home/vr/torch/install/share/lua/5.1/threads/queue.lua:65: in function </home/vr/torch/install/share/lua/5.1/threads/queue.lua:41>
	[C]: in function 'pcall'
	/home/vr/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
	[string "  local Queue = require 'threads.queue'..."]:13: in main chunk
stack traceback:
	[C]: in function 'error'
	/home/vr/torch/install/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
	/home/vr/torch/install/share/lua/5.1/threads/threads.lua:264: in function 'synchronize'
	/home/vr/torch/install/share/lua/5.1/threads/threads.lua:142: in function 'specific'
	/home/vr/torch/install/share/lua/5.1/threads/threads.lua:125: in function 'Threads'
	/home/vr/deepmask/DataLoader.lua:41: in function '__init'
	/home/vr/torch/install/share/lua/5.1/torch/init.lua:91: in function </home/vr/torch/install/share/lua/5.1/torch/init.lua:87>
	[C]: in function 'DataLoader'
	/home/vr/deepmask/DataLoader.lua:21: in function 'create'
	evalPerPatch.lua:77: in main chunk
	[C]: in function 'dofile'
	...e/vr/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d50

How solve this problem?   thank you!

**Comment by yeates** [comment]
would you tell us how to solve this ? thx!

**Comment by Minilei89** [comment]
Assertion error tends to happen when the script cannot locate the file. If you're running the training and eval based on the readme, then it's quite likely you did not place the instances_trained2014.json and instances_val2014 in the correct location. They should be in $DEEPMASK/data/annotations/. Do you get this error when running the eval or training script?

**Comment by zchrissirhcz** [comment]
@Minilei89 Hi Minlei, I find you in other issues that provided a good practice for installing correct version of torch for Deepmask/Sharpmask training. Further, as the original paper claims that it comsumes 5 day to train Deepmask and 2 days to train Sharpmask (on K40m), so I would like to directly evaluate the result myself, from the official provided models. However, the two eval scrips just cannot load model.t7 file. Did you meet similar problem? If so, how did you handle that?

i.e. I installed torch with commit of 5961f52a65fe33efa675f71e5c19ad8de56e8dad, and use this:
```
TORCH_LUA_VERSION=LUA52 ./install.sh
```

**Comment by Minilei89** [comment]
@zchrissirhcz It's been a while since I've touched deepmask but if you are not doing any training, perhaps try using luajit instead of lua 5.2. I recall that luajit had no problems with running the pretrained model whereas it had more difficulty in training due to the limited memory luajit is able to use. Also can you post your error log as that will help in identifying the cause of the problem.

**Comment by zchrissirhcz** [comment]
@Minilei89 Thansk. I installed two version of torch, one is with the specific commit you mentioned and with pure lua, and the other is with luajit. The former is OK for training, the latter is OK for evaluation.
