### ISSUE TITLE
Training deepmask from scratch 

### ISSUE THREAD

**Issue by ps48** [facebookresearch/deepmask#94]
I see the option **-scratch** parameter in the code, by default it is set to **false**. But when I explicitly mention the parameter as **true**, I get this error

> ~/torch/deepmask$ th train.lua -batch 1 -scratch true
invalid argument: true

**Comment by chrisckr** [comment]
Lose the "true", just use -scratch.

**Comment by ps48** [comment]
@chrisckr thanks :)
