### ISSUE TITLE
Got stuck while training for a custom dataset

### ISSUE THREAD

**Issue by nirmaljith** [facebookresearch/deepmask#98]
I am using the deep mask for training custom dataset. I could able to run the code without any error, but got stuck after showing the message 'Start training'.
Any clue what is happening ?

**Comment by chrisckr** [comment]
Had the same problem, check the json syntax and compare it to the original character by character. Most certainly you forgot a bracket etc.

**Comment by nirmaljith** [comment]
Hi @chrisckr  , thanks for the reply,  I will check the same. I have one doubt regarding JSON creating.
I am doing the rle encoding of the mask, Is that right think to do or deepmask is expecting polygon encoding ?

**Comment by chrisckr** [comment]
Deepmask wants the jsons to look exactly like the COCO jsons > xy, x1y1, x2y2 polygon coordinates.

**Comment by nirmaljith** [comment]
Thank you very much @chrisckr , I will check this and update the status.

**Comment by nirmaljith** [comment]
Earlier i was giving the segmentation in **rle** encoded form. After changing it to polygon encoding the code started working properly.

Code got stuck because of a while loop present in the **DataSampler.lua**
`  while not ann or ann.iscrowd == 1 or ann.area < 100 or ann.bbox[3] < 5
    or ann.bbox[4] < 5 do`

To resolve this issue i made the iscrowd value 0 in my JSON. Anyway the code started working, need to check the accuracy once the training is finished.
